const desc = {
    SandboxMode: [
        ['text', 'string'],
    ],
    CastleMode: [
        ['text', 'string'],
    ],
    DominationMode: [
        ['score', 'always'],
        ['state_key', 'key'],
        ['text', 'string'],
        ['winner', 'int'],
    ],
    BattleRoyaleMode: [
        ['state_key', 'key'],
        ['text', 'string'],
        ['radius', 'int'],
    ],
    update: [
        ['queue', 'always'],
        ['entities', 'always'],
        ['sharedKeys', 'notempty'],
    ],
    private_data: [
        ['tx', 'int'],
        ['ty', 'int'],
        ['score', 'int'],
    ],
    Tribesman: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['group_sid', 'int'],
        ['health', 'float'],
        ['equipment', 'int'],
        ['occupation', 'int'],
        ['status', 'int'],
        ['x', 'int'],
        ['y', 'int'],
        ['parent_sid', 'int'],
    ],
    Tribe: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
        ['team', 'int'],
        ['score', 'int'],
        ['name', 'string'],
        ['stay', 'bool'],
    ],
    Castle: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
        ['name', 'string'],
        ['score', 'int'],
        ['team', 'int'],
    ],
    Building: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
        ['key', 'key'],
        ['health', 'int'],
        ['node_sid', 'int'],
        ['angle', 'float'],
        ['state_key', 'key'],
        ['connections', 'int'],
        ['counter', 'int'],
        ['team', 'int'],
        ['float1', 'float'],
        ['key1', 'key'],
        ['int1', 'int'],
        ['cooldown', 'float'],
        ['operator_sid', 'int'],
    ],
    Animal: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['group_sid', 'int'],
        ['health', 'float'],
        ['occupation', 'int'],
        ['status', 'int'],
        ['kind', 'key'],
        ['x', 'int'],
        ['y', 'int'],
    ],
    Herd: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
    ],
    Monster: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['group_sid', 'int'],
        ['x', 'int'],
        ['y', 'int'],
        ['health', 'int'],
        ['occupation', 'int'],
    ],
    Campfire: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
        ['state', 'bool'],
    ],
    Tree: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['parent_sid', 'int'],
        ['state', 'int'],
        ['x', 'int'],
        ['y', 'int'],
    ],
    Plant: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
        ['key', 'key'],
        ['grown', 'float'],
    ],
    Meadow: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
        ['radius', 'int'],
        ['grass', 'int'],
        ['team', 'int'],
        ['water', 'float'],
    ],
    Rocks: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['parent_sid', 'int'],
        ['count', 'int'],
    ],
    Mushroom: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['parent_sid', 'int'],
        ['key', 'int'],
    ],
    Collectible: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['x', 'int'],
        ['y', 'int'],
        ['from', 'int'],
        ['key', 'key'],
    ],
    Cloud: [
        ['sid', 'always'],
        ['constructorName', 'key'],
        ['remove', 'bool',
            '_remove'],
        ['sharedX', 'int'],
        ['sharedY', 'int'],
        ['target_sid', 'int'],
    ],
    hit: [
        ['entity', 'int'],
        ['hull', 'float'],
        ['direction', 'float'],
    ],
    resources: [
        ['food', 'int'],
        ['wood', 'int'],
        ['gold', 'int'],
        ['water', 'int'],
    ],
    invent: [
        ['key', 'key'],
    ],
    operate: [
        ['sid', 'int'],
        ['int1', 'int'],
        ['int2', 'int'],
        ['float1', 'float'],
        ['float2', 'float'],
    ],
};

const keys = [
    1, "snapshot", 1, "snapshot", 
    2, "SandboxMode", 3, "CastleMode", 4,
    "DominationMode", 5,
    "BattleRoyaleMode", 6, "update", 7,
    "private_data", 8, "Tribesman", 9,
    "Tribe", 10, "Castle", 11,
    "Building", 12, "Animal", 13,
    "Herd", 14, "Monster", 15,
    "Campfire", 16, "Tree", 17, "Plant",
    18, "Meadow", 19, "Rocks", 20,
    "Mushroom", 21, "Collectible", 22,
    "Cloud", 23, "hit", 24, "resources",
    25, "invent", 26, "operate", 27,
    "nothing", 28, "axe", 29, "hammer",
    30, "sword", 31, "wizard_staff", 32,
    "scythe", 33, "bow", 34, "dagger",
    35, "backpack", 36, "wooden_shield",
    37, "reinforced_shield", 38,
    "steel_shield", 39, "hood", 40,
    "wizard_hat", 41, "viking_helmet",
    42, "legion_helmet", 43, "crown",
    44, "noble_cape", 45, "wood", 46,
    "stone", 47, "chest", 48, "gold",
    49, "food", 50, "water", 51,
    "iron_stone", 52, "copper_stone",
    53, "gold_stone", 54, "mushroom_1",
    55, "mushroom_2", 56, "mushroom_3",
    57, "mushroom_4", 58, "mushroom_5",
    59, "mushroom_6", 60, "mushroom_7",
    61, "mushroom_8", 62, "mushroom_9",
    63, "mushroom_10", 64, "lumberjack",
    65, "windmill", 66, "shock_arrow",
    67, "butchery", 68, "cannibalism",
    69, "mycology", 70, "stay", 71,
    "farming", 72, "shoes", 73, "saw",
    74, "corn", 75, "tree_plant", 76,
    "missionary", 77, "wood_storage",
    78, "food_storage", 79, "well", 80,
    "stationary_catapult", 81,
    "stone_wall", 82, "stone_gate", 83,
    "stone_node", 84, "stone_tower", 85,
    "emote_alert", 86, "finished", 87,
    null, 88, "rabbit", 89, "wireframe",
    90, "empty", 91, "destroyed", 92,
    "loaded", 93, "aim", 94, "fire", 95,
    "cooldown"
]

module.exports = {
    desc: desc,
    keys: keys,
}